In [10]:
import numpy as np
arr=np.array([7,4,3,5,1])

In [11]:
def bubblesort(arr):
    n=len(arr)
    for i in range(n):
        c=0
        for j in range(n-i-1):
            if(arr[j]>arr[j+1]):
                temp=arr[j]
                arr[j]=arr[j+1]
                arr[j+1]=temp
                c+=1
            print(arr)
        if(c==0):
            break

In [12]:
print(arr)
print("working")
bubblesort(arr)


[7 4 3 5 1]
working
[4 7 3 5 1]
[4 3 7 5 1]
[4 3 5 7 1]
[4 3 5 1 7]
[3 4 5 1 7]
[3 4 5 1 7]
[3 4 1 5 7]
[3 4 1 5 7]
[3 1 4 5 7]
[1 3 4 5 7]
