In [13]:
import numpy as np
arr=np.array([7,4,3,5,1])

In [14]:
def insertionsort(arr):
    n=len(arr)
    for i in range(1,n):
        key=arr[i]
        j=i-1
        while(j>=0 and arr[j]>key):
            arr[j+1]=arr[j]
            j-=1
        arr[j+1]=key
        print(arr)

In [15]:
print(arr)
print("working")
insertionsort(arr)


[7 4 3 5 1]
working
[4 7 3 5 1]
[3 4 7 5 1]
[3 4 5 7 1]
[1 3 4 5 7]
