In [17]:
import numpy as np
arr=np.array([7,4,3,5,1])

In [18]:
def selectionsort(arr):
    n=len(arr)
    for i in range(n):
        m=arr[i]
        ind=i
        for j in range(i+1,n):
            if(arr[j]<m):
                m=arr[j]
                ind=j
        temp=arr[i]
        arr[i]=arr[ind]
        arr[ind]=temp
        print(arr)
        

In [19]:
print(arr)
print("working")
selectionsort(arr)


[7 4 3 5 1]
working
[1 4 3 5 7]
[1 3 4 5 7]
[1 3 4 5 7]
[1 3 4 5 7]
[1 3 4 5 7]
